travis:
  secure:
    BINSTAR_TOKEN: nCiblJlO65Hh7u26xxwU9Z9OtlNsI8MQzM2+sKb6wbo/W6ho5H8UkaUteZQYSN5mAJA3NJ7wWmw5CePJ2LN7rz0ILKg+wUslUAeUuplu8lGkvNqSgorfrn1g5QtUWEKOogyXPHOgv4SamZ1d/z9C/WkHCTWLmbs8r+DZaKY9/R/ND4C/oqkNMomTJfOhBQAEKxtBv8MGiPWoEKT0T249O0SMS7xsOdl080d7tTKL/Hl+pgGNgsEZVJxeUI+/VAobt4rcSiUaJo78xTnpVJLi4gGNH/JrAhAZTDqmvQv2nu4Yg3yw+rEoOXGK3d0lHJWYDEN/uSkA83+hqLhTcKPCsQdW2OuWApj+3Sa1trkw69WV4F+i5ExOEIqfxPZHl/CLx2jJ2Uls2uJ4ohmda9fUeb/BqtW3ygTN1NW0f2p0N2WDq0gWrXR11P1wR03QH++KAiDgJDJ00+NfQdCgIVAvr5C5b8LTdoO9UHeBd6RRSZm3BJpPMMOv3D974IqP5tDXmMkA/LsSAKwa5xrth+OzVx1Wl8m7ueGlUbLTMFXmq+9OOuR/ETGIEB2MNvzEf4k1GQrXbOp7NG7nSju6Xl5m3ssbzlrVLfITWYf1MEWAKZjuymXt/aDsgKXBDoMQ2+2vBmS2NHyASmY2pwzOHpCLaXx49y/o2vTS0e9Q8r41Eqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
